export const DEMO = [
    {
        "id": "demo-coffee",
        "name": "Coffee, slowly",
        "kind": "photo",
        "mime": "image/jpeg",
        "width": 600,
        "height": 400,
        "src": "./media/coffee.jpg",
        "credit": "Rachel Michetti / Pikolo Espresso Bar \u00b7 CC0-1.0",
        "creator": "Rachel Michetti / Pikolo Espresso Bar",
        "license": "CC0-1.0",
        "source": "https://scikit-image.org/docs/stable/api/skimage.data.html#skimage.data.coffee",
        "modifications": "JPEG re-encoding for local app; crops/grades only within editable compositions."
    },
    {
        "id": "demo-garden",
        "name": "Garden afternoon",
        "kind": "photo",
        "mime": "image/jpeg",
        "width": 640,
        "height": 427,
        "src": "./media/garden.jpg",
        "credit": "Daniel B\u00fcchele \u00b7 CC-BY-2.0",
        "creator": "Daniel B\u00fcchele",
        "license": "CC-BY-2.0",
        "source": "https://www.flickr.com/photos/danielbuechele/6061409035/",
        "modifications": "JPEG re-encoding for local app; crops/grades only within editable compositions."
    },
    {
        "id": "demo-flower",
        "name": "A little bloom",
        "kind": "photo",
        "mime": "image/jpeg",
        "width": 640,
        "height": 427,
        "src": "./media/flower.jpg",
        "credit": "vultilion \u00b7 CC-BY-2.0",
        "creator": "vultilion",
        "license": "CC-BY-2.0",
        "source": "https://www.flickr.com/photos/vultilion/6056698931/",
        "modifications": "JPEG re-encoding for local app; crops/grades only within editable compositions."
    },
    {
        "id": "demo-cat",
        "name": "At home with Chelsea",
        "kind": "photo",
        "mime": "image/jpeg",
        "width": 451,
        "height": 300,
        "src": "./media/cat.jpg",
        "credit": "Stefan van der Walt \u00b7 CC0-1.0",
        "creator": "Stefan van der Walt",
        "license": "CC0-1.0",
        "source": "https://scikit-image.org/docs/stable/api/skimage.data.html#skimage.data.chelsea",
        "modifications": "JPEG re-encoding for local app; crops/grades only within editable compositions."
    },
    {
        "id": "demo-astronaut",
        "name": "Portrait in orbit",
        "kind": "photo",
        "mime": "image/jpeg",
        "width": 512,
        "height": 512,
        "src": "./media/astronaut.jpg",
        "credit": "NASA \u00b7 Public domain",
        "creator": "NASA",
        "license": "Public domain",
        "source": "https://flic.kr/p/r9qvLn",
        "modifications": "JPEG re-encoding for local app; crops/grades only within editable compositions."
    },
    {
        "id": "demo-rocket",
        "name": "Night launch",
        "kind": "photo",
        "mime": "image/jpeg",
        "width": 640,
        "height": 427,
        "src": "./media/rocket.jpg",
        "credit": "SpaceX \u00b7 Public domain",
        "creator": "SpaceX",
        "license": "Public domain",
        "source": "https://www.flickr.com/photos/spacexphotos/16511594820/",
        "modifications": "JPEG re-encoding for local app; crops/grades only within editable compositions."
    },
    {
        "id": "demo-cosmos",
        "name": "Far from ordinary",
        "kind": "photo",
        "mime": "image/jpeg",
        "width": 1000,
        "height": 872,
        "src": "./media/cosmos.jpg",
        "credit": "NASA / ESA \u00b7 Public domain",
        "creator": "NASA / ESA",
        "license": "Public domain",
        "source": "https://hubblesite.org/contents/media/images/2012/37/3060-Image.html",
        "modifications": "JPEG re-encoding for local app; crops/grades only within editable compositions."
    },
    {
        "id": "demo-camera",
        "name": "The observer",
        "kind": "photo",
        "mime": "image/jpeg",
        "width": 512,
        "height": 512,
        "src": "./media/camera.jpg",
        "credit": "Lav Varshney \u00b7 CC0-1.0",
        "creator": "Lav Varshney",
        "license": "CC0-1.0",
        "source": "https://scikit-image.org/docs/stable/api/skimage.data.html#skimage.data.camera",
        "modifications": "JPEG re-encoding for local app; crops/grades only within editable compositions."
    },
    {
        "id": "demo-coast",
        "name": "Coastal study \u2014 original illustration",
        "kind": "photo",
        "mime": "image/svg+xml",
        "width": 800,
        "height": 1000,
        "src": "./media/coast.svg",
        "creator": "Stillroll contributors",
        "license": "MIT",
        "source": "Original vector artwork authored for this project",
        "modifications": "None",
        "credit": "Original Stillroll sample illustration \u2022 MIT"
    },
    {
        "id": "demo-alpine",
        "name": "Alpine study \u2014 original illustration",
        "kind": "photo",
        "mime": "image/svg+xml",
        "width": 800,
        "height": 1000,
        "src": "./media/alpine.svg",
        "creator": "Stillroll contributors",
        "license": "MIT",
        "source": "Original vector artwork authored for this project",
        "modifications": "None",
        "credit": "Original Stillroll sample illustration \u2022 MIT"
    },
    {
        "id": "demo-desert",
        "name": "Desert study \u2014 original illustration",
        "kind": "photo",
        "mime": "image/svg+xml",
        "width": 800,
        "height": 1000,
        "src": "./media/desert.svg",
        "creator": "Stillroll contributors",
        "license": "MIT",
        "source": "Original vector artwork authored for this project",
        "modifications": "None",
        "credit": "Original Stillroll sample illustration \u2022 MIT"
    },
    {
        "id": "demo-night",
        "name": "City after hours \u2014 original illustration",
        "kind": "photo",
        "mime": "image/svg+xml",
        "width": 800,
        "height": 1000,
        "src": "./media/night.svg",
        "creator": "Stillroll contributors",
        "license": "MIT",
        "source": "Original vector artwork authored for this project",
        "modifications": "None",
        "credit": "Original Stillroll sample illustration \u2022 MIT"
    },
    {
        "id": "demo-road",
        "name": "Open road \u2014 original illustration",
        "kind": "photo",
        "mime": "image/svg+xml",
        "width": 800,
        "height": 1000,
        "src": "./media/road.svg",
        "creator": "Stillroll contributors",
        "license": "MIT",
        "source": "Original vector artwork authored for this project",
        "modifications": "None",
        "credit": "Original Stillroll sample illustration \u2022 MIT"
    },
    {
        "id": "demo-forest",
        "name": "Forest study \u2014 original illustration",
        "kind": "photo",
        "mime": "image/svg+xml",
        "width": 800,
        "height": 1000,
        "src": "./media/forest.svg",
        "creator": "Stillroll contributors",
        "license": "MIT",
        "source": "Original vector artwork authored for this project",
        "modifications": "None",
        "credit": "Original Stillroll sample illustration \u2022 MIT"
    },
    {
        "id": "demo-flowers",
        "name": "Botanical study \u2014 original illustration",
        "kind": "photo",
        "mime": "image/svg+xml",
        "width": 800,
        "height": 1000,
        "src": "./media/flowers.svg",
        "creator": "Stillroll contributors",
        "license": "MIT",
        "source": "Original vector artwork authored for this project",
        "modifications": "None",
        "credit": "Original Stillroll sample illustration \u2022 MIT"
    }
];
